services:
  front-end:
    container_name: front-end
    build: .
    image: front-end
    ports:
      - 80:80
#    networks:
#      - my-network
  
#networks:
#  my-network:
#    name: my-network
#    external: true